CREATE TABLE USER_T (
    USER_ID         VARCHAR(16)     NOT NULL,
    PASSWORD        VARCHAR(50)     NOT NULL,
    FIRST_NAME      VARCHAR(50)     NOT NULL,
    LAST_NAME       VARCHAR(50)     NOT NULL,
    PRIMARY KEY (USER_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;